-- Fungal BGC Atlas relational schema
-- Generated by scripts/build_database.py from the source workbook.
-- Every table shares `dossier_id` as its join key back to BGC.

CREATE TABLE BGC (
    dossier_id TEXT,
    mibig_accession TEXT,
    source_database TEXT,
    mibig_version TEXT,
    organism_key TEXT,
    organism_name TEXT,
    strain_primary_key TEXT,
    strain_primary_raw TEXT,
    ncbi_taxon_id TEXT,
    primary_sequence_accession TEXT,
    reported_start_bp TEXT,
    reported_end_bp TEXT,
    reported_length_bp TEXT,
    reported_bgc_boundary TEXT,
    mibig_bgc_class_raw TEXT,
    refined_bgc_class_raw TEXT,
    product_family_raw TEXT,
    primary_product_raw TEXT,
    chemical_class_raw TEXT,
    biological_role_raw TEXT,
    primary_reference_doi TEXT,
    primary_reference_year TEXT,
    source_sheet_title TEXT
);
CREATE INDEX idx_bgc_dossier_id ON BGC (dossier_id);
CREATE INDEX idx_bgc_organism_key ON BGC (organism_key);
CREATE INDEX idx_bgc_strain_primary_key ON BGC (strain_primary_key);

CREATE TABLE ORGANISM (
    organism_key TEXT,
    organism_name TEXT,
    ncbi_taxon_id TEXT,
    phylum TEXT,
    class TEXT,
    order TEXT,
    family TEXT,
    genus TEXT,
    ecological_lifestyle_raw TEXT,
    first_dossier_id TEXT
);
CREATE INDEX idx_organism_organism_key ON ORGANISM (organism_key);

CREATE TABLE STRAIN (
    strain_key TEXT,
    organism_key TEXT,
    strain_label_raw TEXT,
    dossier_id_first_seen TEXT,
    role_first_seen TEXT
);
CREATE INDEX idx_strain_strain_key ON STRAIN (strain_key);
CREATE INDEX idx_strain_organism_key ON STRAIN (organism_key);

CREATE TABLE BGC_FACET (
    facet_id TEXT,
    dossier_id TEXT,
    facet_axis TEXT,
    raw_value TEXT,
    missingness_state TEXT,
    normalized_value TEXT,
    normalization_status TEXT,
    source_ids TEXT,
    source_row TEXT
);
CREATE INDEX idx_bgc_facet_dossier_id ON BGC_FACET (dossier_id);
CREATE INDEX idx_bgc_facet_facet_axis ON BGC_FACET (facet_axis);

CREATE TABLE GENE (
    gene_key TEXT,
    dossier_id TEXT,
    gene_id TEXT,
    gene_name TEXT,
    protein_accession TEXT,
    start_bp TEXT,
    end_bp TEXT,
    strand TEXT,
    predicted_function_raw TEXT,
    demonstrated_function_raw TEXT,
    perturbation_raw TEXT,
    phenotype_raw TEXT,
    source_ids TEXT,
    note TEXT,
    source_row TEXT
);
CREATE INDEX idx_gene_dossier_id ON GENE (dossier_id);

CREATE TABLE METABOLITE (
    metabolite_key TEXT,
    dossier_id TEXT,
    metabolite_id TEXT,
    name_raw TEXT,
    congener_or_variant_raw TEXT,
    formula TEXT,
    structure_id TEXT,
    chemical_role_raw TEXT,
    bioactivity_raw TEXT,
    recovery_location_raw TEXT,
    identification_level_raw TEXT,
    source_ids TEXT,
    note TEXT,
    source_row TEXT
);
CREATE INDEX idx_metabolite_dossier_id ON METABOLITE (dossier_id);

CREATE TABLE EXPERIMENT (
    experiment_key TEXT,
    dossier_id TEXT,
    experiment_id TEXT,
    organism_key TEXT,
    strain_key TEXT,
    strain_raw TEXT,
    source_ids TEXT,
    note TEXT,
    source_row TEXT
);
CREATE INDEX idx_experiment_dossier_id ON EXPERIMENT (dossier_id);
CREATE INDEX idx_experiment_experiment_key ON EXPERIMENT (experiment_key);
CREATE INDEX idx_experiment_organism_key ON EXPERIMENT (organism_key);
CREATE INDEX idx_experiment_strain_key ON EXPERIMENT (strain_key);

CREATE TABLE TERM (
    term_id TEXT,
    term_type TEXT,
    raw_label TEXT,
    canonical_label TEXT,
    normalization_status TEXT
);
CREATE INDEX idx_term_term_id ON TERM (term_id);
CREATE INDEX idx_term_term_type ON TERM (term_type);

CREATE TABLE EXPERIMENT_LINK (
    experiment_link_id TEXT,
    experiment_key TEXT,
    relation_type TEXT,
    term_id TEXT,
    raw_value TEXT,
    source_ids TEXT,
    source_row TEXT
);
CREATE INDEX idx_experiment_link_experiment_key ON EXPERIMENT_LINK (experiment_key);
CREATE INDEX idx_experiment_link_term_id ON EXPERIMENT_LINK (term_id);

CREATE TABLE MEASUREMENT (
    measurement_key TEXT,
    dossier_id TEXT,
    measurement_id TEXT,
    subject_type TEXT,
    subject_id TEXT,
    analyte_raw TEXT,
    value_raw TEXT,
    value_numeric TEXT,
    unit_raw TEXT,
    denominator_raw TEXT,
    timepoint_raw TEXT,
    statistic_raw TEXT,
    n_raw TEXT,
    detection_limit_raw TEXT,
    direction_vs_control_raw TEXT,
    source_ids TEXT,
    note TEXT,
    source_row TEXT
);
CREATE INDEX idx_measurement_dossier_id ON MEASUREMENT (dossier_id);
CREATE INDEX idx_measurement_subject_id ON MEASUREMENT (subject_id);

CREATE TABLE OBSERVATION (
    observation_id TEXT,
    dossier_id TEXT,
    experiment_key TEXT,
    observation_type TEXT,
    subject_type TEXT,
    subject_id TEXT,
    value_raw TEXT,
    measurement_scale TEXT,
    timepoint_raw TEXT,
    source_ids TEXT,
    source_row TEXT,
    normalization_status TEXT
);
CREATE INDEX idx_observation_dossier_id ON OBSERVATION (dossier_id);
CREATE INDEX idx_observation_experiment_key ON OBSERVATION (experiment_key);

CREATE TABLE CLAIM (
    claim_key TEXT,
    dossier_id TEXT,
    claim_id TEXT,
    claim_text TEXT,
    evidence_type_raw TEXT,
    direct_or_inferred_raw TEXT,
    supporting_detail_raw TEXT,
    caveat_raw TEXT,
    source_ids TEXT,
    source_row TEXT
);
CREATE INDEX idx_claim_dossier_id ON CLAIM (dossier_id);

CREATE TABLE RELATIONSHIP (
    relationship_key TEXT,
    dossier_id TEXT,
    relationship_id TEXT,
    subject_raw TEXT,
    predicate_raw TEXT,
    object_raw TEXT,
    relationship_text_raw TEXT,
    source_ids TEXT,
    note TEXT,
    source_row TEXT,
    normalization_status TEXT
);
CREATE INDEX idx_relationship_dossier_id ON RELATIONSHIP (dossier_id);
CREATE INDEX idx_relationship_predicate_raw ON RELATIONSHIP (predicate_raw);

CREATE TABLE CONFLICT (
    conflict_key TEXT,
    dossier_id TEXT,
    conflict_id TEXT,
    issue_type_raw TEXT,
    description_raw TEXT,
    evidence_A_raw TEXT,
    evidence_B_raw TEXT,
    interpretation_raw TEXT,
    status_raw TEXT,
    source_ids TEXT,
    source_row TEXT
);
CREATE INDEX idx_conflict_dossier_id ON CONFLICT (dossier_id);
CREATE INDEX idx_conflict_issue_type_raw ON CONFLICT (issue_type_raw);

CREATE TABLE SOURCE (
    source_key TEXT,
    dossier_id TEXT,
    source_id TEXT,
    source_type_raw TEXT,
    year_raw TEXT,
    title_or_database_raw TEXT,
    doi_or_accession_raw TEXT,
    pmid_raw TEXT,
    url_raw TEXT,
    note TEXT,
    source_row TEXT
);
CREATE INDEX idx_source_dossier_id ON SOURCE (dossier_id);
CREATE INDEX idx_source_source_id ON SOURCE (source_id);

CREATE TABLE EVIDENCE_LINK (
    evidence_link_id TEXT,
    record_type TEXT,
    record_key TEXT,
    dossier_id TEXT,
    source_id TEXT,
    source_key TEXT,
    link_status TEXT,
    record_source_row TEXT
);
CREATE INDEX idx_evidence_link_dossier_id ON EVIDENCE_LINK (dossier_id);
CREATE INDEX idx_evidence_link_record_type ON EVIDENCE_LINK (record_type);
CREATE INDEX idx_evidence_link_record_key ON EVIDENCE_LINK (record_key);
CREATE INDEX idx_evidence_link_source_key ON EVIDENCE_LINK (source_key);

CREATE TABLE ASSERTION (
    assertion_id TEXT,
    dossier_id TEXT,
    section TEXT,
    field TEXT,
    value_raw TEXT,
    missingness_state TEXT,
    source_ids TEXT,
    source_row TEXT,
    feature_policy TEXT
);
CREATE INDEX idx_assertion_dossier_id ON ASSERTION (dossier_id);
CREATE INDEX idx_assertion_section ON ASSERTION (section);

CREATE TABLE COMPACT_FACT (
    compact_fact_id TEXT,
    dossier_id TEXT,
    section TEXT,
    source_row TEXT,
    fact_type TEXT,
    label_raw TEXT,
    statement_raw TEXT,
    source_ids TEXT,
    extra_raw_json TEXT,
    normalization_status TEXT
);
CREATE INDEX idx_compact_fact_dossier_id ON COMPACT_FACT (dossier_id);

CREATE TABLE COVERAGE (
    dossier_id TEXT,
    mibig_accession TEXT,
    organism_name TEXT,
    facets TEXT,
    genes TEXT,
    metabolites TEXT,
    experiments TEXT,
    measurements TEXT,
    claims TEXT,
    relationships TEXT,
    conflicts TEXT,
    sources TEXT,
    normalization_queue_rows TEXT
);
CREATE INDEX idx_coverage_dossier_id ON COVERAGE (dossier_id);

CREATE TABLE DOSSIER_SCHEMA (
    dossier_id TEXT,
    section TEXT,
    row_count TEXT,
    first_token TEXT,
    header_present TEXT,
    standard_section TEXT
);
CREATE INDEX idx_dossier_schema_dossier_id ON DOSSIER_SCHEMA (dossier_id);
CREATE INDEX idx_dossier_schema_section ON DOSSIER_SCHEMA (section);

CREATE TABLE NORMALIZATION_QUEUE (
    queue_id TEXT,
    dossier_id TEXT,
    section TEXT,
    source_row TEXT,
    reason TEXT,
    status TEXT
);
CREATE INDEX idx_normalization_queue_dossier_id ON NORMALIZATION_QUEUE (dossier_id);
CREATE INDEX idx_normalization_queue_status ON NORMALIZATION_QUEUE (status);

CREATE TABLE PROVENANCE_EXCLUDED (
    dossier_id TEXT,
    source_row TEXT,
    field TEXT,
    excluded_value_present TEXT,
    reason TEXT,
    source_ids TEXT
);
CREATE INDEX idx_provenance_excluded_dossier_id ON PROVENANCE_EXCLUDED (dossier_id);

CREATE TABLE RAW_ROW (
    dossier_id TEXT,
    section TEXT,
    source_row TEXT,
    raw_json TEXT
);
CREATE INDEX idx_raw_row_dossier_id ON RAW_ROW (dossier_id);
CREATE INDEX idx_raw_row_section ON RAW_ROW (section);
