"""build_database.py — load the processed CSVs into a documented SQLite database.

Writes db/schema.sql (human-readable schema, generated from the actual
column types pandas inferred) and data/db/fungal_bgc_atlas.db. Asserts every
table's row count against config.EXPECTED_COUNTS (taken verbatim from the
source workbook's SUMMARY sheet) so a parsing regression fails the build
immediately instead of silently drifting from the real data.
"""
from __future__ import annotations
import sqlite3
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.config import DATA_SHEETS, DB_PATH, EXPECTED_COUNTS, PROCESSED_DIR, SCHEMA_SQL

# Indices on the columns actually used to join across tables (all joins in
# this schema go through dossier_id; a few tables also carry a second key).
INDEX_COLUMNS = {
    "BGC": ["dossier_id", "organism_key", "strain_primary_key"],
    "ORGANISM": ["organism_key"],
    "STRAIN": ["strain_key", "organism_key"],
    "BGC_FACET": ["dossier_id", "facet_axis"],
    "GENE": ["dossier_id"],
    "METABOLITE": ["dossier_id"],
    "EXPERIMENT": ["dossier_id", "experiment_key", "organism_key", "strain_key"],
    "TERM": ["term_id", "term_type"],
    "EXPERIMENT_LINK": ["experiment_key", "term_id"],
    "MEASUREMENT": ["dossier_id", "subject_id"],
    "OBSERVATION": ["dossier_id", "experiment_key"],
    "CLAIM": ["dossier_id"],
    "RELATIONSHIP": ["dossier_id", "predicate_raw"],
    "CONFLICT": ["dossier_id", "issue_type_raw"],
    "SOURCE": ["dossier_id", "source_id"],
    "EVIDENCE_LINK": ["dossier_id", "record_type", "record_key", "source_key"],
    "ASSERTION": ["dossier_id", "section"],
    "COMPACT_FACT": ["dossier_id"],
    "COVERAGE": ["dossier_id"],
    "DOSSIER_SCHEMA": ["dossier_id", "section"],
    "NORMALIZATION_QUEUE": ["dossier_id", "status"],
    "PROVENANCE_EXCLUDED": ["dossier_id"],
    "RAW_ROW": ["dossier_id", "section"],
}


def build_database() -> None:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    if DB_PATH.exists():
        DB_PATH.unlink()
    con = sqlite3.connect(DB_PATH)

    schema_lines = [
        "-- Fungal BGC Atlas relational schema",
        "-- Generated by scripts/build_database.py from the source workbook.",
        "-- Every table shares `dossier_id` as its join key back to BGC.",
        "",
    ]

    for name in DATA_SHEETS:
        csv_path = PROCESSED_DIR / f"{name.lower()}.csv"
        df = pd.read_csv(csv_path)

        n = len(df)
        expected = EXPECTED_COUNTS.get(name)
        if expected is not None:
            assert n == expected, f"{name}: expected {expected} rows, parsed {n}"

        df.to_sql(name, con, if_exists="replace", index=False)

        cols_sql = ",\n".join(f"    {c} TEXT" for c in df.columns)
        schema_lines.append(f"CREATE TABLE {name} (\n{cols_sql}\n);")
        for col in INDEX_COLUMNS.get(name, []):
            if col in df.columns:
                idx = f"idx_{name.lower()}_{col}"
                con.execute(f'CREATE INDEX "{idx}" ON "{name}" ("{col}")')
                schema_lines.append(f'CREATE INDEX {idx} ON {name} ({col});')
        schema_lines.append("")

        print(f"  {name:<22} {n:>7,} rows -> table {name}")

    con.commit()
    con.close()

    SCHEMA_SQL.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_SQL.write_text("\n".join(schema_lines))
    print(f"\nWrote {DB_PATH.relative_to(DB_PATH.parents[2])} and {SCHEMA_SQL.relative_to(SCHEMA_SQL.parents[1])}")


if __name__ == "__main__":
    build_database()
